---
version: "3"

services:
  front:
    build:
      context: front
      target: dev
    restart: always
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3001
    environment:
      - EMAIL_PASS=${EMAIL_PASS}
      - NOCODB_TOKEN=${NOCODB_TOKEN}
