---
version: "3"

services:
  export:
    image: ghcr.io/bvpyro/bvpk-export:dev
    container_name: export
    volumes:
      - /srv/bvpk/export:/app/output
    environment:
      - POETRY_NOCODB_TOKEN=${NOCODB_TOKEN}
