---
version: "3"

services:
  database:
    image: postgres:13
    container_name: directus-db
    restart: always
    volumes:
      - /home/dockeruser/bvpk/directus-db:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      POSTGRES_DB: "directus"
    healthcheck:
      test: pg_isready -U directus -d directus
      interval: 10s
      timeout: 2s
      retries: 10
    logging:
      driver: journald

  cache:
    restart: always
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    restart: always
    container_name: directus
    image: directus/directus:v9.0.0-rc.74
    ports:
      - 8055:8055
    volumes:
      - /home/dockeruser/bvpk/uploads:/directus/uploads
    networks:
      - directus
      - web
    depends_on:
      - cache
      - database
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"

      ADMIN_EMAIL: admin@sehn.dev
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.directus.loadbalancer.server.port=8055"
      - "traefik.http.routers.directus.rule=Host(`bvpk-back.linus.cx`)"
      - "traefik.http.routers.directus.entrypoints=https"
      - "traefik.http.routers.directus.tls=true"
      - "traefik.http.routers.directus.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.directus-https.redirectscheme.scheme=https"
      - "traefik.http.routers.directus-http.entrypoints=http"
      - "traefik.http.routers.directus-http.rule=Host(`bvpk-back.linus.cx`)"
      - "traefik.http.routers.directus-http.middlewares=directus-https@docker"

    logging:
      driver: journald

networks:
  directus:
    internal: true
    name: directus
  web:
    external: true
    name: web
