---
version: "3"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2
    restart: always
    volumes:
      - /home/dockeruser/bvpk/filebrowser:/srv
      - /home/dockeruser/bvpk/filebrowser/database.db:/database.db
      - /home/dockeruser/bvpk/filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 8081:8081
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=8081"
      - "traefik.http.routers.filebrowser.rule=Host(`files.bvpk.org`)"
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.filebrowser-https.redirectscheme.scheme=https"
      - "traefik.http.routers.filebrowser-http.entrypoints=http"
      - "traefik.http.routers.filebrowser-http.rule=Host(`files.bvpk.org`)"
      - "traefik.http.routers.filebrowser-http.middlewares=filebrowser-https@docker"
    logging:
      driver: journald

networks:
  web:
    external:
      name: web
