---
version: "3"

services:
  nocodb-db:
    image: postgres:13
    container_name: nocodb-db
    restart: always
    volumes:
      - /home/dockeruser/bvpk/nocodb-db:/var/lib/postgresql/data
    networks:
      - web
    environment:
      POSTGRES_USER: "nocodb"
      POSTGRES_PASSWORD: ${NOCODB_DB_PASSWORD}
      POSTGRES_DB: "nocodb"
    healthcheck:
      test: pg_isready -U nocodb -d nocodb
      interval: 10s
      timeout: 2s
      retries: 10

  nocodb:
    container_name: nocodb
    image: nocodb/nocodb:0.9.35
    restart: always
    networks:
      - web
    environment:
      - NC_DB=pg://nocodb-db:5432?u=nocodb&p=${NOCODB_DB_PASSWORD}&d=nocodb
      - NC_PUBLIC_URL=https://nocodb.sehn.dev
      - NC_DISABLE_TELE=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nocodb.loadbalancer.server.port=8080"
      - "traefik.http.routers.nocodb.rule=Host(`nocodb.sehn.dev`)"
      - "traefik.http.routers.nocodb.entrypoints=https"
      - "traefik.http.routers.nocodb.tls=true"
      - "traefik.http.routers.nocodb.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.nocodb-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nocodb-http.entrypoints=http"
      - "traefik.http.routers.nocodb-http.rule=Host(`bvpk-back.linus.cx`)"
      - "traefik.http.routers.nocodb-http.middlewares=nocodb-https@docker"
    depends_on:
      - nocodb-db
