---
version: '3'

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: next/starter:0.0.1
    container_name: next
    restart: always
    networks:
      - web
    ports:
      - '3001:3001'
    labels:
      # global redirect to https
      - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.entrypoints=http'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'

      # middleware redirect
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'

      # # middleware redirect to www
      # - 'traefik.http.middlewares.redirect-to-www.redirectregex.regex=(https|http)://(?:www.)?(.*)'
      # - 'traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.$${2}'
      # - 'traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true'

      # # middleware redirect to non-www
      # - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.regex=(https|http)://(www\\.(.*))"
      # - 'traefik.http.middlewares.redirect-to-nonwww.redirectregex.replacement=https://$${3}'
      # - 'traefik.http.middlewares.redirect-to-nonwww.redirectregex.permanent=true'

      # next traefik setup
      - 'traefik.enable=true'
      - 'traefik.http.services.next.loadbalancer.server.port=3001'
      - 'traefik.http.routers.next.rule=Host(`bvpk-front.linux.cx`)'
      - 'traefik.http.routers.next.entrypoints=https'
      - 'traefik.http.routers.next.tls=true'
      - 'traefik.http.routers.next.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.next.service=next'
      # - 'traefik.http.routers.next.middlewares=redirect-to-www'

networks:
  web:
    external:
      name: web
