---
version: '3'

services:
  next-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
