---
version: '3'

services:
  front:
    container_name: bvpk-front
    build:
      context: .
      target: prod
      image: bvpk-front:0.3.0
    restart: always
    ports:
      - 3001:3001
    environment:
      - EMAIL_PASS=${EMAIL_PASS}
      - NOCODB_TOKEN=${NOCODB_TOKEN}
    labels:
      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # # middleware redirect to non-www
      - traefik.http.middlewares.redirect-to-nonwww.redirectregex.regex=(https|http)://(www\.(.*))
      - traefik.http.middlewares.redirect-to-nonwww.redirectregex.replacement=https://$${3}
      - traefik.http.middlewares.redirect-to-nonwww.redirectregex.permanent=true
      # next traefik setup
      - traefik.enable=true
      - traefik.http.services.next.loadbalancer.server.port=3001
      - traefik.http.routers.next.rule=Host(`bvpk.org`,`www.bvpk.org`)
      - traefik.http.routers.next.entrypoints=https
      - traefik.http.routers.next.tls=true
      - traefik.http.routers.next.tls.certresolver=letsencrypt
      - traefik.http.routers.next.service=next
      - traefik.http.routers.next.middlewares=redirect-to-nonwww
    logging:
      driver: journald
    networks:
      - web

networks:
  web:
    external:
      name: web
