---
name: build and publish bvpk-export

on:
  schedule:
    - cron: "45 4 * * *"
  push:
    branches:
      - main
    paths:
      - "export/**"
      - ".github/workflows/build-and-publish-bvpk-export.yml"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/bvpyro/bvpk-export
          tags: |
            type=sha
            type=ref,event=branch
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push Docker image for export
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: export
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-publish-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.export.yml to server
        uses: appleboy/scp-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.export.yml"
          target: "/srv/bvpk/"

      - name:
        uses: appleboy/ssh-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NOCODB_TOKEN="${{ secrets.NOCODB_TOKEN }}"
            docker-compose -f /srv/bvpk/docker-compose.export.yml pull
            docker-compose -f /srv/bvpk/docker-compose.export.yml up -d
