---
name: Push new export script to server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.export.yml to server
        uses: appleboy/scp-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "export/to_csv.py,export/pyproject.toml,export/poetry.lock"
          target: "/srv/bvpk/"

      - name:
        uses: appleboy/ssh-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/bvpk/export
            export POETRY_NOCODB_TOKEN="${{ secrets.NOCODB_TOKEN }}"
            ~/.local/bin/poetry install
            ~/.local/bin/poetry run python3 to_csv.py
