name: Deploy the services

on:
  push:
    branches:
      - prod
      - dev

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/srv/bvpk/"

      - name: Copy filebrowser config
        uses: appleboy/scp-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./filebrowser/config.json"
          target: "/srv/bvpk/"

      - name:
        uses: appleboy/ssh-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export CMS_DB_PASSWORD="${{ secrets.CMS_DB_PASSWORD }}"
            export CMS_KEY="${{ secrets.CMS_KEY }}"
            export CMS_SECRET="${{ secrets.CMS_SECRET }}"
            export CMS_ADMIN_PASSWORD="${{ secrets.CMS_ADMIN_PASSWORD }}"
            export NOCODB_DB_PASSWORD="${{ secrets.NOCODB_DB_PASSWORD }}"
            export EMAIL_PASS="${{ secrets.EMAIL_PASS }}"
            export NOCODB_TOKEN="${{ secrets.NOCODB_TOKEN }}"
            docker-compose -f /srv/bvpk/docker-compose.yml pull
            docker-compose -f /srv/bvpk/docker-compose.yml up -d
