name: Run export

on:
  schedule:
    - cron: "0,30 * * * *"
  push:
    branches:
      - prod
      - dev

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.export.yml to server
        uses: appleboy/scp-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.export.yml"
          target: "/srv/bvpk/"

      - name:
        uses: appleboy/ssh-action@master
        with:
          host: h2952128.stratoserver.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NOCODB_TOKEN="${{ secrets.NOCODB_TOKEN }}"
            docker-compose -f /srv/bvpk/docker-compose.export.yml pull
            docker-compose -f /srv/bvpk/docker-compose.export.yml up -d
